spring:
  datasource:
    url: ${DATASOURCE_URL:}
    username: ${DATASOURCE_USERNAME:}
    password: ${DATASOURCE_PASSWORD:}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/unisys
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DLL:update}
    show-sql: ${JPA_SHOW_SQL:true}